### PR TITLE
Platforms: HiSilicon: Sync devicetree with linux kernel 4.19.5

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
Sync the devicetree with 4.19.5 linux kernel used for builds.

Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by b49020** [comment]
Please update hi3660-hikey960.dtb file too.

**Comment by Mani-Sadhasivam** [comment]
@b49020 It was already updated, only DTS sync is needed now.

**Comment by b49020** [comment]
@Mani-Sadhasivam Ok, but I think for GPU node you might need to update dtb as well :).

**Comment by Mani-Sadhasivam** [comment]
@b49020 Oh yes ;-)

**Comment by Mani-Sadhasivam** [comment]
@b49020 Done!

**Comment by b49020** [comment]
@Mani-Sadhasivam Thanks.

`Reviewed-by: Sumit Garg <sumit.garg@linaro.org>`

**Comment by b49020** [comment]
@hzhuang1 Do you have any comments on this PR? If not, then please help to merge this PR.

**Pull request merged**
